version: 2
jobs:
  "ubuntu":
    docker:
      - image: ubuntu:18.04
        environment:
          CC: clang-6.0
          CFLAGS: "-march=native -std=c++17"
    steps:
      - checkout

      - run: apt-get update -qq
      - run: >
          apt-get install -y
          build-essential
          clang-6.0
          python3.7
          python3.7-dev
          python3-pip
          python3-setuptools
          python3.7-venv

      - run:
          name: Updating python dependencies
          command: |
            python3.7 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --upgrade setuptools
            pip install pytest

      - run:
          name: Building (no-cython)
          command: |
            . venv/bin/activate
            python setup.py install
            pip uninstall -y pysimdjson

      - run:
          name: Building (cython)
          command: |
            . venv/bin/activate
            pip install cython
            python setup.py install

      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest

      - run:
          name: Ensure package can be installed
          command: |
            . venv/bin/activate
            pip install dist/pysimdjson-*.tar.gz
            pip uninstall -y pysimdjson

workflows:
  version: 2
  build_and_test:
    jobs:
      - "ubuntu"
