version: 2
jobs:
  "ubuntu":
    docker:
      - image: ubuntu:18.04
        environment:
          CC: clang-6.0
    steps:
      - checkout

      - run: apt-get update -qq
      - run: >
          apt-get install -y
          build-essential
          clang-6.0
          python3.7
          python3.7-dev
          python3-pip
          python3-setuptools
          python3.7-venv

      - run:
          name: Updating python dependencies
          command: |
            python3.7 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --upgrade setuptools
            pip install pytest

      - run:
          name: Building (no-cython)
          command: |
            . venv/bin/activate
            python setup.py install
            pip uninstall -y pysimdjson

      - run:
          name: Building (cython)
          command: |
            . venv/bin/activate
            pip install cython
            python setup.py install

      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest

      - store_artifacts:
          path: dist

      - run:
          name: Ensure package can be installed (cython)
          command: |
            . venv/bin/activate
            pip uninstall -y pysimdjson
            python setup.py sdist
            pip install pysimdjson --no-index --find-links file:dist --no-binary :all:
            pip uninstall -y pysimdjson

      - run:
          name: Ensure package can be installed (no-cython)
          command: |
            . venv/bin/activate
            pip uninstall -y cython
            pip uninstall -y pysimdjson
            python setup.py sdist
            pip install pysimdjson --no-index --find-links file:dist --no-binary :all:
            pip uninstall -y pysimdjson

  "manylinux":
    docker:
      - image: tktechdocker/manylinux:gcc8.3.0
        environment:
          # Do not use -march=native, we may miss out on some optimizations but
          # we want to work on any machines with AVX2.
          CFLAGS: "-march=haswell -std=c++17 -static-libstdc++"
          CC: /usr/local/gcc-8.3.0/bin/gcc-8.3.0
          CXX: /usr/local/gcc-8.3.0/bin/g++-8.3.0

    steps:
      - checkout

      - run: /opt/python/cp34-cp34m/bin/python setup.py bdist_wheel
      - run: /opt/python/cp35-cp35m/bin/python setup.py bdist_wheel
      - run: /opt/python/cp36-cp36m/bin/python setup.py bdist_wheel
      - run: /opt/python/cp37-cp37m/bin/python setup.py bdist_wheel
      - run: /opt/python/cp34-cp34m/bin/python setup.py bdist_wheel
      - run: /opt/python/cp35-cp35m/bin/python setup.py bdist_wheel
      - run: /opt/python/cp36-cp36m/bin/python setup.py bdist_wheel
      - run: /opt/python/cp37-cp37m/bin/python setup.py bdist_wheel

      - run:
          name: Running auditwheel...
          command: |
              for whl in dist/*.whl; do
                  auditwheel repair "$whl";
               done

      - store_artifacts:
          path: wheelhouse

      - run:
           name: Uploading to pypi
           command: |
               /opt/python/cp37-cp37m/bin/pip install twine
               /opt/python/cp37-cp37m/bin/twine upload wheelhouse/*

workflows:
  version: 2
  build_and_test:
    jobs:
      - "ubuntu"
      - "manylinux":
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
